name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install Cordova
      run: npm install -g cordova

    - name: Install dependencies (if needed)
      run: |
        if [ -f package.json ]; then
          npm install
        fi

    - name: Add Android platform
      run: cordova platform add android

    - name: Add Cordova TTS plugin
      run: cordova plugin add cordova-plugin-tts

    - name: Build APK
      run: cordova build android

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: apk-build-artifact
        path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
